name: py_env
 channels:
    - conda-forge
 dependencies:
 - pre-commit=2.4.0
 - networkx=2.2
 - numpy=1.17.3
 - pandas=1.0.5
 - python-dateutil=2.8.1
 - pytz=2019.3
 - six=1.13.0
 - xlrd=1.2.0
 - dill=0.3.1.1
 - llvmlite=0.30.0
 - numba=0.46.0
 - thrift=0.11.0
 - python-snappy=0.5.4
 - tqdm=4.38.0
 - joblib=0.14.0
 - scikit-learn=0.21.3
 - scipy=1.3.2
 - PyWavelets=1.1.1
 - cycler=0.10.0
 - decorator=4.4.1
 - imageio=2.6.1
 - kiwisolver=1.1.0
 - matplotlib=3.1.1
 - pillow=6.2.1
 - pyparsing=2.4.4
 - scikit-image=0.16.2
 - ipynb-py-convert=0.4.4
 - catboost=0.20.2
 - folium=0.10.0
 - ipython=7.9.0
 - certifi=2019.9.11
 - chardet=3.0.4
 - idna=2.8
 - requests=2.22.0
 - urllib3=1.25.7
 - lxml=4.4.1
 - bayesian-optimization=1.0.1
 - hyperopt=0.2.2
 - psutil=5.6.7
 - pip
 - python=3.7
 - rpy2=2.9.4
 - utm
 - jupyter
 - mlflow=1.6.0
 - fastparquet=0.3.3
 - geopandas=0.7.0
 - seaborn=0.10.0
 - shap=0.32.1
 - plotly=4.7.1
 - pandasql=0.7.3
 - pip:
   - rdp==0.8
   - smopy==0.0.7
   - hausdorff==0.2.2
   - pandarallel==1.4.1
   - configargparse==1.0
   - pyproj==2.6.0
   - luigi==3.0.0
